{
 "title": "Docker Monitoring",
 "description": "Docker Monitoring Template",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{instance=~\"$server:.*\"}) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes{instance=~\"$server:.*\"}+node_memory_Cached_bytes{instance=~\"$server:.*\"}) ) / sum(node_memory_MemTotal_bytes{instance=~\"$server:.*\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total{instance=~\"$server:.*\",image!=\"\"}[1m] ) )) / count(node_cpu_seconds_total{instance=~\"$server:.*\",mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "Container Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{instance=~\"$server:.*\"} - container_fs_usage_bytes{instance=~\"$server:.*\"}) / sum(container_fs_limit_bytes{instance=~\"$server:.*\"})"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_cpu_user_seconds_total{instance=~\"$server:.*\",image!=\"\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{instance=~\"$server:.*\",image!=\"\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Total Network i/o",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_network_receive_bytes_total{instance=~\"$server:.*\",image!=\"\"}[1m] ) )",
     "legendFormat": "{{ Receive }}"
    },
    {
     "expr": "sum by (container_name) (rate(container_network_transmit_bytes_total{instance=~\"$server:.*\",image!=\"\"}[1m] ) )",
     "legendFormat": "{{ Transmit }}"
    }
   ]
  }
 ]
}