{
 "title": "Unifi Controller Dashboard",
 "description": "A Grafana dashboard to utilize with the Ubiquiti UniFi exporter.",
 "tags": [
  "network",
  "unifi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Client",
    "query": "label_values(unifi_stations_received_bytes_total,hostname)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(unifi_devices_uptime_seconds_total,name)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifi_devices_wireless_transmitted_bytes_total{name=~\"$device\"}[$interval])) by (name)",
     "legendFormat": "tx-{{name}}"
    },
    {
     "expr": "- sum(rate(unifi_devices_wireless_received_bytes_total{name=~\"$device\"}[$interval])) by (name)",
     "legendFormat": "rx-{{name}}"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(unifi_devices_wireless_transmitted_packets_dropped_total{name=~\"$device\"}[$interval])) by (name)",
     "legendFormat": "{{name}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Wireless Device Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(unifi_stations_transmitted_bytes_total{connection=\"wireless\"}[$interval])) by (ap_mac)",
     "legendFormat": "tx-{{ap_mac}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "- sum(rate(unifi_stations_received_bytes_total{connection=\"wireless\"}[$interval])) by (ap_mac)",
     "legendFormat": "rx-{{ap_mac}}"
    }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unifi_stations_transmitted_bytes_total{hostname=~\"$client\"}[$interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "- sum(rate(unifi_stations_received_bytes_total{hostname=~\"$client\"}[$interval]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Client",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(unifi_stations_transmitted_bytes_total{hostname=~\"$client\"}[$interval])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Recieved Network Traffic per Client",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(unifi_stations_received_bytes_total{hostname=~\"$client\"}[$interval])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(unifi_stations_transmitted_bytes_total{hostname=~\"$client\"}[$interval])) by (hostname)",
     "legendFormat": "{{hostname}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Device Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "unifi_devices_uptime_seconds_total",
     "legendFormat": "{{name}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Wifi Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "unifi_devices_stations_user", "legendFormat": "user-{{name}} {{radio}}" },
    { "expr": "unifi_devices_stations_guest", "legendFormat": "guest-{{name}} {{radio}}" }
   ]
  },
  {
   "title": "Wireless APs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(unifi_devices_stations) by (name, mac)",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}