{
 "title": "Weather",
 "tags": [ "weather" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "City",
    "query": "label_values(weather_time, city)"
   }
  ]
 },
 "panels": [
  {
   "title": "Local Date/Time (Your local time)",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 }
  },
  {
   "title": "Current Temperature (F)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_temperature{city=~\"$City\"}"
    }
   ]
  },
  {
   "title": "Current Humidity (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_humidity{city=~\"$City\"} * 100"
    }
   ]
  },
  {
   "title": "Nearest Storm (miles)",
   "type": "singlestat",
   "description": "Current distance in miles from the current location of the closest storm.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "lengthmi",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_nearest_storm_distance{city=~\"$City\"}"
    }
   ]
  },
  {
   "title": "Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Temperature (F)" }
   ],
   "targets": [
    {
     "expr": "weather_temperature{city=~\"$City\"}",
     "legendFormat": "Temperature (F)"
    },
    {
     "expr": "weather_dew_point{city=~\"$City\"}",
     "legendFormat": "Dew Point (F)"
    },
    {
     "expr": "weather_apparent_temperature{city=~\"$City\"}",
     "legendFormat": "Feels Like (F)"
    }
   ]
  },
  {
   "title": "Relative Humidity (%)",
   "type": "graph",
   "description": "Humidity Percentage",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Percentage (%)" }
   ],
   "targets": [
    {
     "expr": "avg(weather_humidity{city=~\"$City\"}) * 100",
     "legendFormat": "Relative Humidity (%)"
    },
    {
     "expr": "weather_precip_probability{city=~\"$City\"}",
     "legendFormat": "Precipitation Probability (%)"
    },
    {
     "expr": "weather_cloud_cover{city=~\"$City\"}",
     "legendFormat": "Sky Cover (%)"
    }
   ]
  },
  {
   "title": "Barometric Pressure (inHg)",
   "type": "graph",
   "description": "Barometric Pressure",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Inches of Mercury" }
   ],
   "targets": [
    {
     "expr": "weather_pressure{city=~\"$City\"} * 0.00029530",
     "legendFormat": "Barometric Pressure"
    }
   ]
  },
  {
   "title": "Wind (mph)",
   "type": "graph",
   "description": "Wind Speed",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Miles Per Hour" }
   ],
   "targets": [
    {
     "expr": "weather_wind_speed{city=~\"$City\"}",
     "legendFormat": "Wind Speed (mph)"
    },
    {
     "expr": "weather_wind_gust{city=~\"$City\"}",
     "legendFormat": "Wind Gust (mph)"
    }
   ]
  },
  {
   "title": "Rain (Inches)",
   "type": "graph",
   "description": "Precipatation",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Inches" }
   ],
   "targets": [
    {
     "expr": "weather_precip_intensity{city=~\"$City\"}",
     "legendFormat": "Rain (in.)"
    }
   ]
  }
 ]
}